AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Runtime: nodejs8.10
Resources:
  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: sts:AssumeRole
          Principal:
            Service: lambda.amazonaws.com
      Policies:
      - PolicyName: WriteCloudWatchLogs
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*
      - PolicyName: UpdateUserPoolClient
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action: cognito-idp:UpdateUserPoolClient
            Resource: arn:aws:cognito-idp:*:*:userpool/*
      - PolicyName: ManageUserPoolDomain
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action: cognito-idp:CreateUserPoolDomain
            Resource:
            - arn:aws:cognito-idp:us-west-2:934150036772:userpool/*
            - arn:aws:cognito-idp:*:*:userpool/*
          - Effect: Allow
            Action: cognito-idp:DeleteUserPoolDomain
            Resource: arn:aws:cognito-idp:*:*:userpool/*
          - Effect: Allow
            Action: cognito-idp:DescribeUserPoolDomain
            Resource: '*'
      - PolicyName: InvokeLambdaFunction
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action: lambda:InvokeFunction
            Resource:
            - arn:aws:lambda:us-west-2:934150036772:function:CloudFormationSendResponse
            - arn:aws:lambda:*:*:function:*
  CloudFormationSendResponse:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambdas/CloudFormationSendResponse/index.handler
      CodeUri: s3://cognito-bucket-temp5/778e353a774eb810c732a451daf48034
  CFCognitoUserPoolDomain:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambdas/CloudFormationCognitoUserPoolDomain.handler
      CodeUri: s3://cognito-bucket-temp5/778e353a774eb810c732a451daf48034
    DependsOn: CloudFormationSendResponse
  AppUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: dev4-user-pool
      UsernameAttributes:
      - email
      AutoVerifiedAttributes:
      - email
  AppUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: dev4-user-pool-client
      UserPoolId:
        Ref: AppUserPool
      ExplicitAuthFlows:
      - ADMIN_NO_SRP_AUTH
      GenerateSecret: false
  UserPoolDomain:
    Type: Custom::CognitoUserPoolDomain
    Properties:
      ServiceToken:
        Fn::GetAtt:
        - CFCognitoUserPoolDomain
        - Arn
      UserPoolId:
        Ref: AppUserPool
      Domain: userpool-himanshu-sample-01
Parameters:
  ParamProjectName:
    Type: String
  ParamENV:
    Type: String
  ParamBucket:
    Type: String
Outputs:
  UserPoolId:
    Value:
      Ref: AppUserPool
  UserPoolClientId:
    Value:
      Ref: AppUserPoolClient
