AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Runtime: nodejs8.10
Resources:
  LambdaCognito:
    Type: AWS::IAM::Role
    Properties:
      RoleName: LambdaCognito
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: sts:AssumeRole
          Principal:
            Service: lambda.amazonaws.com
      Policies:
      - PolicyName: WriteCloudWatchLogs
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*
      - PolicyName: UpdateUserPoolClient
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action: cognito-idp:UpdateUserPoolClient
            Resource: arn:aws:cognito-idp:*:*:userpool/*
      - PolicyName: ManageUserPoolDomain
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action: cognito-idp:CreateUserPoolDomain
            Resource:
            - arn:aws:cognito-idp:us-west-2:934150036772:userpool/*
            - arn:aws:cognito-idp:*:*:userpool/*
          - Effect: Allow
            Action: cognito-idp:DeleteUserPoolDomain
            Resource: arn:aws:cognito-idp:*:*:userpool/*
          - Effect: Allow
            Action: cognito-idp:DescribeUserPoolDomain
            Resource: '*'
      - PolicyName: InvokeLambdaFunction
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action: lambda:InvokeFunction
            Resource:
            - arn:aws:lambda:*:*:function:*
  CFCognitoUserPoolDomain:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambdas/CloudFormationCognitoUserPoolDomain.handler
      Role:
        Fn::GetAtt:
        - LambdaCognito
        - Arn
      CodeUri: s3://cognito-bucket-sam/89618935ffe8668d3a179f904a688c5b
    DependsOn: CloudFormationSendResponse
  CFCognitoUserPoolClientSettings:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambdas/CloudFormationCognitoUserPoolClientSettings.handler
      Role:
        Fn::GetAtt:
        - LambdaCognito
        - Arn
      CodeUri: s3://cognito-bucket-sam/89618935ffe8668d3a179f904a688c5b
    DependsOn: CloudFormationSendResponse
  CloudFormationSendResponse:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambdas/CloudFormationSendResponse/index.handler
      Role:
        Fn::GetAtt:
        - LambdaCognito
        - Arn
      CodeUri: s3://cognito-bucket-sam/89618935ffe8668d3a179f904a688c5b
  AppUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: dev-user-pool
      UsernameAttributes:
      - email
      AutoVerifiedAttributes:
      - email
  AppUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: dev-user-pool-client
      UserPoolId:
        Ref: AppUserPool
      ExplicitAuthFlows:
      - ADMIN_NO_SRP_AUTH
      GenerateSecret: false
  UserPoolDomain:
    Type: Custom::CognitoUserPoolDomain
    Properties:
      ServiceToken:
        Fn::GetAtt:
        - CFCognitoUserPoolDomain
        - Arn
      UserPoolId:
        Ref: AppUserPool
      Domain: userpool-himanshu-sample-cog
  UserPoolClientSettings:
    Type: Custom::CognitoUserPoolClientSettings
    Properties:
      ServiceToken:
        Fn::GetAtt:
        - CFCognitoUserPoolClientSettings
        - Arn
      UserPoolId:
        Ref: AppUserPool
      UserPoolClientId:
        Ref: AppUserPoolClient
      SupportedIdentityProviders:
      - COGNITO
      CallbackURL: https://www.amazon.com
      LogoutURL: https://www.google.com
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows:
      - code
      AllowedOAuthScopes:
      - openid
Parameters:
  ParamProjectName:
    Type: String
  ParamENV:
    Type: String
  ParamBucket:
    Type: String
Outputs:
  UserPoolId:
    Value:
      Ref: AppUserPool
  UserPoolClientId:
    Value:
      Ref: AppUserPoolClient
